[package]
name = "aoc23-10-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = { version = "2.1.0", optional = true }

[features]
visualise = ["dep:colored"]
